"use client";

/**
 * Home Page with React Flow Diagram
 * Generated by Roo
 */
import dynamic from "next/dynamic";

const FlowPageClient = dynamic(() => import("../components/FlowPageClient"), {
  ssr: false,
});

export default function Home() {
  return <FlowPageClient />;
}
